catch curl

diff --git a/.github/workflows/ci.auto_deploy_staging.yml b/.github/workflows/ci.auto_deploy_staging.yml
--- a/.github/workflows/ci.auto_deploy_staging.yml
+++ b/.github/workflows/ci.auto_deploy_staging.yml
@@ -15,14 +15,21 @@ jobs:
 
     - name: Build
       run: |
-          CODE=`curl --write-out '%{http_code}' --location --request GET 'https://appsmith.staging-green.manabie.io/api/v1/git/pull/app/6360798db3ce396b06d52e39' \
+          HTTP_RESPONSE=$(curl --location --request GET 'https://appsmith.staging-green.manabie.io/api/v1/git/pull/app/6360798db3ce396b06d52e39' \
           --header 'Accept: application/json, text/plain, */*' \
           --header 'branchName: master' \
-          --header 'Authorization: Basic YXBwc21pdGhAbWFuYWJpZS5jb206TUBuYWJpZTEyMw=='`
-          if [ $CODE!="200" ] 
-          then
-              echo "FAILURE"
-          else
-              echo "SUCCESS"
+          --header 'Authorization: Basic YXBwc21pdGhAbWFuYWJpZS5jb206TUBuYWJpZTEyMw==')
+          # extract the body
+          HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
+
+          # extract the status
+          HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+
+          # print the body
+          echo "$HTTP_BODY"
+
+          # example using the status
+          if [ ! $HTTP_STATUS -eq 200  ]; then
+            echo "Error [HTTP status: $HTTP_STATUS]"
+            exit 1
           fi
-          
